version: '3'
services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
    - "5672:5672"
    - "15672:15672"
  pgsql:
    image: "postgres:11"
    ports:
    - "5432:5432"
    environment:
    - "POSTGRES_PASSWORD=postgres"
#  pauta:
#    build: .
#    ports:
#    - 8080:8080
#    depends_on:
#    - pg
#    - rabbitmq